name: Poke-for-Party-and-Friends
version: ${project.version}
author: Simonsator
depends: [PartyAndFriends]
main: de.simonsator.partyandfriends.extensions.PokeMain
description: An add-on for party and friends to add the command /friend poke
